version: "3"
services:
  web:
    image: couchdb
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - "3184:5984"
    volumes:
      - /data/couchdb/:/opt/couchdb/data/
      - "./local.ini:/opt/couchdb/etc/local.d/local.ini"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "9000:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - webnet
networks:
  webnet:
